services:
  manul-bot:
    build:
      context: ./BOT/
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - manul-network
    
  manul-db:
    image: postgres:alpine
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - manul-db-volume:/var/lib/postgresql/data
    networks:
      - manul-network
  
  manul-backend:
    build: 
      context: ./BACKEND/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - manul-network
    depends_on:
      manul-db:
        condition: service_healthy

networks:
  manul-network:

volumes:
  manul-db-volume: 
